version: "3.8"
services:
  telegram_bot_mommyramona:
    container_name: telegram_bot_mommyramona
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "8081:8080"
    volumes:
      - .:/app
    command: python /app/main.py
